Rails動画教材ページの実装
yanbaru-expert/team_project_54 pull request #39
Opened 2021-07-23 20:01 UTC by tomoki1230

close #15

## 実装内容

- モデルにRailsジャンルリストを定義
- Rails動画教材の一覧ページを作成
  - 表示するジャンルを制限
  - レンダリングを使用
  - Bootstrap用いてレイアウトを作成
  - 各動画にレベル表示を入れる
  - カードの下側部分に`height` を指定し高さを揃える
  - 動画教材専用のcssを作成し、実装

## 参考資料

- [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
- [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)
- [【公式】Embeds](https://getbootstrap.com/docs/4.5/utilities/embed/)
- [【やんばるエキスパート教材】YouTube動画の投稿](https://www.yanbaru-code.com/texts/349)
- [Railsのpartialでcollectionを渡すときにはindexの変数が自動的に作られる](https://qiita.com/otakumesi/items/74a75cd6ebff7eba5c63)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-07-24 14:21 UTC, great084 requested changes

2021-07-24 14:21 UTC, great084 commented on app/assets/stylesheets/movies.scss
> +}
.btn クラスに幅設定をするのではなく、全幅となる.btn-blockクラスを利用すると良いと思います。
※bootstrapで定義されているクラスに上書きでスタイル設定するのは、基本的にはやめたほうが良いです。

2021-07-24 14:41 UTC, tomoki1230 commented on app/assets/stylesheets/movies.scss
> +}
かしこまりました。ご指摘ありがとうございます。
修正しましたので、お手数ですが再度ご確認をお願いいたします。

2021-07-26 13:02 UTC, great084 approved these changes
LGTMです！

2021-07-26 13:26 UTC, merged